### ISSUE TITLE
Зачем нужен БазовыйКаталог

### ISSUE THREAD

**Issue by shalimski** [oscript-library/tempfiles#10]
Не понял зачем нужна экспортная переменная "БазовыйКаталог", которая используется только в функции НовоеИмяФайла, и объединяется с полученным именем, в случае если БазовыйКаталог заполнен. Но ведь ПолучитьИмяВременногоФайла вернет полное имя файла, зачем его может потребоваться с чем-то объединять?

**Comment by EvilBeaver** [comment]
Дайте пример кода, пожалуйста. Не очень понятно о чем речь

**Comment by shalimski** [comment]
`
Функция НовоеИмяФайла(Знач Расширение = "tmp") Экспорт
	
	ИмяВремФайла = ПолучитьИмяВременногоФайла(Расширение);
	Если ЗначениеЗаполнено(БазовыйКаталог) Тогда
		ИмяВремФайла = ОбъединитьПути(БазовыйКаталог, ИмяВремФайла);
	КонецЕсли;
	
	мВременныеФайлы.Добавить(ИмяВремФайла);
	
	Возврат ИмяВремФайла;
	
КонецФункции
`

**Comment by shalimski** [comment]
[Вот где ты его добавил](https://github.com/oscript-library/tempfiles/commit/49b0e20786b89969aa4c752f21a66af1894e4eec)

**Comment by EvilBeaver** [comment]
Теперь ясно. БазовыйКаталог - это каталог, который не в Temp а где-то еще, по указанию пользователя библиотеки. Т.е. если надо например временные файлы генерировать в currentdir

**Comment by shalimski** [comment]
Всё понятно, не правильно представлял себе как работает ОбъединитьПути.
Спасибо!
