### ISSUE TITLE
Пространство имен в справке

### ISSUE THREAD

**Issue by codenull** [oscript-library/tempfiles#4]
Здравствуйте.

Пожалуйста, добавте в описание библиотеки название пространства имен: **ВременныеФайлы**.
Из-за специфики импорта библиотек oscript, непонятно из какого пространства имен нужно вызывать методы.

Импорт в таком виде:
`
#Использовать tempfiles
`
А вызов методов такой:
`ВременныйКаталог = ВременныеФайлы.СоздатьКаталог();`

Это не является очевидным.

**Comment by EvilBeaver** [comment]
Спасибо, да, действительно это не отражено в справке. Прелесть опенсорса в том, что вы можете сами отредактировать любую справку, прямо в браузере в интерфейсе гитхаба. Просто
 нажмите edit в файле readme и впишите любой удобный текст. Потомки вам скажут спасибо )
